services:
  app:
    build: .
    #command: bash -c "cd app && alembic revision --autogenerate && alembic upgrade head && python __init__.py"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - '8501:8501'
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"

  db:
    image: postgres
    container_name: pg-docker
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
